### ISSUE TITLE
The /ct merchant command doesn't appear to be working

### ISSUE THREAD

**Issue by belathus** [DevOnTheRocks/RockyTweaks#10]
We're running version 0.4.0 on Minecraft 1.12.2.

I can't see the merchant command on my headless server. Typing it in only gives me a "No such command!" error. I see the mod in the server's log, so I know it is installed.

The screenshot below was taken through my cellphone's SSH app.

![screenshot_2018-05-28-20-12-08](https://user-images.githubusercontent.com/3826783/40632328-ac3a5168-62b3-11e8-8880-95871ce6bc5b.png)

**Comment by Mohron** [comment]
I'll check into this. Maybe something changed on the CraftTweaker side and I just need to update my mod.

**Comment by Mohron** [comment]
Can't Reproduce. 
Used:
![image](https://user-images.githubusercontent.com/3623122/41254079-1d8a7758-6d77-11e8-83bf-18b6f21a1708.png)

**Comment by Robijnvogel** [comment]
I can confirm this.
I am using the latest CT and RC as of this moment on MC 1.12.2
