### ISSUE TITLE
Zero level cost for anvil recipe?

### ISSUE THREAD

**Issue by CommanderTvis** [DevOnTheRocks/RockyTweaks#12]
I want to make recipes of metal plates in the anvil. But I can't set level cost of 0. 

`import mods.rockycore.Anvil;

Anvil.addRecipe(<embers:ingot_copper>, <embers:ingot_copper>, <embers:plate_copper>, 0);`

returns 
![image](https://user-images.githubusercontent.com/38042667/44000214-3ef4a99a-9e46-11e8-8f74-78412bae3086.png)

`import mods.rockycore.Anvil;

Anvil.addRecipe(<embers:ingot_copper>, <embers:ingot_copper>, <embers:plate_copper>);`

returns
![image](https://user-images.githubusercontent.com/38042667/44000241-c4d206d4-9e46-11e8-9163-c25cfdbc74b8.png)

Here are CraftTweaker logs: 
https://gist.github.com/CommanderTvis/1d888472106a769462faaef5b0d16dee

**Comment by brisingraerowing** [comment]
It appears that RockyCore requires MTLib for the Anvil recipes. Install that and it should work.

**Comment by CommanderTvis** [comment]
Add it as Curse depedency, please.

**Comment by Mohron** [comment]
It already is... https://minecraft.curseforge.com/projects/rocky-core/files/2537198

**Comment by CommanderTvis** [comment]
Ok, close issue please
