### ISSUE TITLE
Recipe with experience cost of 0 is uncraftable

### ISSUE THREAD

**Issue by Laike-Endaril** [DevOnTheRocks/RockyTweaks#15]
I created a recipe (iron + coal = steel) and set the experience cost to 0.  The recipe shows correctly in anvil and JEI but the steel ingot cannot be taken from the output slot.

Changing the experience cost to 1 allows the crafting (no other changes made).

**Comment by Mohron** [comment]
Not possible, unfortunately... 

https://github.com/MinecraftForge/MinecraftForge/issues/1618

**Comment by Laike-Endaril** [comment]
@Mohron I see, thanks for looking into it.

I suppose a workaround could probably be used with a wrapper method and a special case for 0 which adds exactly 1 level to the player immediately before the successful crafting, and then passes 1 into the vanilla method, but that's a bit hacky so I won't officially request it.

**Comment by Mohron** [comment]
I actually thought about that as well! But for now I'll just update the
scripts to error on costs less than 1
