### ISSUE TITLE
How do you remove a Trade?

### ISSUE THREAD

**Issue by StoneLegion** [DevOnTheRocks/RockyTweaks#16]
I tried a few methods but it looks like it's not possible?

**Comment by Mohron** [comment]
At the time that I created the add merchant trade capability, Forge lacked a proper way to access, let alone modify, existing trades. I haven't looked into it since originally adding the feature by that is why there's no support for it.

**Comment by Mohron** [comment]
I took a look at the forge code, and I don't see any sane way to access and modify villager's trades. I'm sure with the right tools (reflection, asm, etc) it would be but I won't be going down that dark path. This can be readdressed when forge provides a proper interface for reading and removing villager's recipes.
