### ISSUE TITLE
Merchant Functions

### ISSUE THREAD

**Issue by Boolyman** [DevOnTheRocks/RockyTweaks#23]
Your comment section on the mod download page is disabled, so I have to ask these here...

Does the craftweaker script support removing trades from villagers?

Is there a script function to clear all trades from a profession, so only the ones we put int will show up?

**Comment by Mohron** [comment]
No, you can't remove trades with Rocky Tweaks. 

It's not really possible with the limited access to villager trades minecraft and forge give mods access to. Unless this changes in later versions, support won't be added either.

**Comment by katubug** [comment]
Sorry for the necromancy, but this mod seems to be able to remove trades: https://github.com/crazysnailboy/VillagerTrades/wiki/Removing-Trades

Perhaps that would help you in some way?
