### ISSUE TITLE
Crafting custom anvil recipe fail

### ISSUE THREAD

**Issue by Zergmazter** [DevOnTheRocks/RockyTweaks#27]
```Anvil.addRecipe(<minecraft:iron_ingot>, <minecraft:iron_chestplate>, <minecraft:iron_chestplate>.withLore(["-With Gloves"]), 1);```

After the 1st to 3rd time crafting this anvil recipe with new chestplates each time, the recipe becomes unavailable for no apparent reason. Tried it with mods and without mods, and the same issue persists.

I noticed the recipe shows on JEI, but at some point after crafting, the output in the recipe will go blank. There is the connection that whenever the recipe output in JEI goes blank, the anvil crafting is also unavailable.

**Comment by Zergmazter** [comment]
Actually I'm having the same issue with all recipes regardless. Tested with and without mods.

**Comment by Mohron** [comment]
Please close this if the new version fixes the issue you were experiencing. If not, please update this issue.

**Comment by Zergmazter** [comment]
It's fixed.
