### ISSUE TITLE
[All Versions] Mob Drops compatibility!

### ISSUE THREAD

**Issue by CluelessPhil** [DevOnTheRocks/RockyTweaks#3]
Mob drop added via CT. With the ability to add a chance of %100 drop or less!

**Comment by Mohron** [comment]
Here's what I'm thinking I'll try to implement:
`import mods.rockycore.Mob`

- [ ] `Mob.addDrop(entity, itemstack, chance);`
- [ ] `Mob.addDrop(entity, itemstack (min), max);`
- [ ] `Mob.removeDrop(entity, itemstack);`
- [ ] `Mob.clearDrops(entity);`
- [ ] Support for Entity Types ie. monster, animal, aquatic, ambient, & boss
- [ ] Support for all entities ie. "*"

**Comment by CluelessPhil** [comment]
Great

**Comment by Mohron** [comment]
This will be PR'd to CraftTweaker instead of added to RockyCore.
