### ISSUE TITLE
Cannot create islands

### ISSUE THREAD

**Issue by WorseWaif** [DevOnTheRocks/RockyTweaks#4]
I try to create an island, and it tells me there was an error. I looked into the server console and it said this

06.08 15:35:25 [Server] INFO at net.mohron.skyclaims.util.ClaimUtil.createSpawnClaimResult(ClaimUtil.java:145) ~[ClaimUtil.class:?]
06.08 15:35:25 [Server] INFO java.lang.NoSuchMethodError: me.ryanhamshire.griefprevention.api.claim.Claim$Builder.cuboid(Z)Lme/ryanhamshire/griefprevention/api/claim/Claim$Builder;
06.08 15:35:25 [Server] Server thread/ERROR [Sponge]: Error occurred while executing command 'is create island' for source EntityPlayerMP['WorseWaif'/85, l='SkyIslands', x=64.37, y=144.05, z=0.16]: me.ryanhamshire.griefprevention.api.claim.Claim$Builder.cuboid(Z)Lme/ryanhamshire/griefprevention/api/claim/Claim$Builder;

I'm not very knowledgeable on all this stuff, but was wondering if it was due to the server being 1.11.2. I know you mentioned in the thread that it would work, though Bloodshot from GriefPrevention stated in the discord that Sky Claims wasn't for 1.11.2 and I had to wait until it was updated. I did get the commands from grief prevention and skyclaims to load finally, and when I do other commands it tells me that I need an island, or that I cant abandon an island claim. When I do /is create it tells me that the island was created and I will be teleported shortly then i get the error. there is no island in /is list, or when i tp to the coordinates mentioned in the console text above.

**Comment by Mohron** [comment]
Why Would you be able to create an Island with https://github.com/DevOnTheRocks/RockyCore?
You might want to try https://github.com/DevOnTheRocks/SkyClaims/issues
