### ISSUE TITLE
Error on world load

### ISSUE THREAD

**Issue by ulk-underscore** [DevOnTheRocks/RockyTweaks#8]
Using either one of the wiki's example usages for anvil recipes results in [this error message](https://imgur.com/a/PSlO5) when the world loads (CraftTweaker v4.1.5, RockyCore v0.4.0). "/ct syntax" doesn't show any errors.

**Comment by Mohron** [comment]
I have no issues loading my test scripts. I'm going to need your script file.
![image](https://user-images.githubusercontent.com/3623122/38476196-0da0b6a4-3b72-11e8-9f36-e5078971d46e.png)

**Comment by ulk-underscore** [comment]
Nevermind, it works with MTLib. I didn't know there is a dependency.

**Comment by Mohron** [comment]
Ya, both CrT and MTlib are dependencies but I have them marked as optional since I originally had more features planned for this mod. I'll probably change this.
